# 10.1 例外処理の基礎
C++には**例外処理**というエラー処理機構が存在します。例外処理とは、何かエラーが起きた箇所で、そのエラーに関する情報を持った**例外オブジェクト**を**投げる**と、その例外を**捕まえる**ことができるまで呼び出し元をさかのぼる機能のことです。

## 10.1.1 throw/try/catch
例外処理にはthrow文とtryブロックそして、（必要に応じて幾つかの）catch節が使われます。
まず、throw文で例外オブジェクトを投げます。その際、tryブロック内から投げられた例外のみが続くcatch節で捕まえられます。もし何もtryブロックで例外が投げられなければ、どのcatch節も実行されず、そのまま次に進みます。
catch節にはそのcatch節が受け取る例外オブジェクトの型を記述できます。記述した方と一致する、もしくはその型の派生クラスの例外オブジェクトが投げられた場合、当該するcatch節の処理がおこなわれます。もし型が一致しなければそのcatch節は何もせず、次のcatch節が例外を捕まえようとします。
throw文はどこでも書けるため、いつでも好きなときに例外を投げることができますが、catch節はtryブロックとセットになって使用しなければならない点に注意してください。
catch節のことを特に**例外ハンドラー**と呼ぶことがあります。
```C++
// tryブロックとcatch節
try {
  statement...
} catch (ype varialbe) {
  statement...
}

// 例外を投げる
throw exception-object;
```

基本的にthrow文で投げることができる例外オブジェクトに対する制限はありませんが、標準ライブラリで提供されているstd::exceptionクラスから派生したクラスを目的に応じて作り、それを投げるのが一般的です。

例外が発生した段階で、処理は直ちにその例外を捕まえることができるcatch節に移ります。
投げられた例外オブジェクトの寿命はcatch節の最後までとなっていて、catch節の処理が正常に終了すると自動的にデストラクターが呼ばれます。

